// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import v1unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

var clusterRoleUnstructuredClusterRole = v1unstructured.Unstructured{
	Object: map[string]any{
		"apiVersion": "rbac.authorization.k8s.io/v1",
		"kind":       "ClusterRole",
		"metadata": map[string]any{
			"name": "cluster-role",
		},
		"rules": []any{
			map[string]any{
				"apiGroups": []any{
					"",
				},
				"resources": []any{
					"persistentvolumes",
				},
				"verbs": []any{
					"get", "list", "watch", "patch",
				},
			}, map[string]any{
				"apiGroups": []any{
					"storage.k8s.io",
				},
				"resources": []any{
					"csinodes",
				},
				"verbs": []any{
					"get", "list", "watch",
				},
			}, map[string]any{
				"apiGroups": []any{
					"storage.k8s.io",
				},
				"resources": []any{
					"volumeattachments",
				},
				"verbs": []any{
					"get", "list", "watch", "patch",
				},
			}, map[string]any{
				"apiGroups": []any{
					"storage.k8s.io",
				},
				"resources": []any{
					"volumeattachments/status",
				},
				"verbs": []any{
					"patch",
				},
			},
		},
	},
}
