// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import (
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var clusterRoleClusterRole = rbacv1.ClusterRole{
	ObjectMeta: metav1.ObjectMeta{
		Name: "cluster-role",
	},
}
