// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import v1unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

var clusterRoleUnstructuredClusterRole = v1unstructured.Unstructured{
	Object: map[string]interface{}{
		"apiVersion": "rbac.authorization.k8s.io/v1",
		"kind":       "ClusterRole",
		"metadata": map[string]interface{}{
			"name": "cluster-role",
		},
		"rules": "[map[apiGroups:[] resources:[persistentvolumes] verbs:[get list watch patch]] map[apiGroups:[storage.k8s.io] resources:[csinodes] verbs:[get list watch]] map[apiGroups:[storage.k8s.io] resources:[volumeattachments] verbs:[get list watch patch]] map[apiGroups:[storage.k8s.io] resources:[volumeattachments/status] verbs:[patch]]]",
	},
}
