// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import (
	appsv1 "k8s.io/api/apps/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var emptydirSampleStatefulSet = appsv1.StatefulSet{
	ObjectMeta: metav1.ObjectMeta{
		Name: "emptydir-sample",
	},
}
