// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import v1unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

var emptydirSampleUnstructuredStatefulSet = v1unstructured.Unstructured{
	Object: map[string]interface{}{
		"apiVersion": "apps/v1",
		"kind":       "StatefulSet",
		"metadata": map[string]interface{}{
			"name": "emptydir-sample",
		},
		"spec": map[string]interface{}{
			"template": map[string]interface{}{
				"spec": map[string]interface{}{
					"volumes": []interface{}{
						map[string]interface{}{
							"name": "socket-dir",
						}, map[string]interface{}{
							"hostPath": map[string]interface{}{
								"path": "/etc/kubernetes",
							},
							"name": "cloud-config",
						}, map[string]interface{}{
							"hostPath": map[string]interface{}{
								"path": "/etc/cacert",
							},
							"name": "cacert",
						},
					},
				},
			},
		},
	},
}
