/*
Boilerplate 2024 test.
*/

// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import (
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var emptydirSampleStatefulSet = appsv1.StatefulSet{
	ObjectMeta: metav1.ObjectMeta{
		Name: "emptydir-sample",
	},
	Spec: appsv1.StatefulSetSpec{
		Template: corev1.PodTemplateSpec{
			Spec: corev1.PodSpec{
				Volumes: []corev1.Volume{
					corev1.Volume{
						Name: "socket-dir",
						VolumeSource: corev1.VolumeSource{
							EmptyDir: &corev1.EmptyDirVolumeSource{},
						},
					},
					corev1.Volume{
						Name: "cloud-config",
						VolumeSource: corev1.VolumeSource{
							HostPath: &corev1.HostPathVolumeSource{
								Path: "/etc/kubernetes",
							},
						},
					},
					corev1.Volume{
						Name: "cacert",
						VolumeSource: corev1.VolumeSource{
							HostPath: &corev1.HostPathVolumeSource{
								Path: "/etc/cacert",
							},
						},
					},
				},
			},
		},
	},
}
