// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import v1unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

var (
	// Unstructured "test2"
	test2UnstructuredNamespace = v1unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "Namespace",
			"metadata": map[string]any{
				"name": "test2",
			},
			"spec":   map[string]any{},
			"status": map[string]any{},
		},
	}

	// Unstructured "pv0004"
	pv0004UnstructuredPersistentVolume = v1unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "PersistentVolume",
			"metadata": map[string]any{
				"name": "pv0004",
			},
			"spec": map[string]any{
				"accessModes": []any{
					"ReadWriteOnce",
				},
				"capacity": map[string]any{
					"storage": "5Gi",
				},
				"mountOptions": []any{
					"hard", "nfsvers=4.1",
				},
				"nfs": map[string]any{
					"path":   "/tmp",
					"server": "172.17.0.2",
				},
				"persistentVolumeReclaimPolicy": "Recycle",
				"storageClassName":              "slow",
				"volumeMode":                    "Filesystem",
			},
		},
	}
)
