// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import v1unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

var (
	// Unstructured "test2"
	test2UnstructuredNamespace = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "Namespace",
			"metadata": map[string]interface{}{
				"name": "test2",
			},
			"spec":   map[string]interface{}{},
			"status": map[string]interface{}{},
		},
	}

	// Unstructured "pv0004"
	pv0004UnstructuredPersistentVolume = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "PersistentVolume",
			"metadata": map[string]interface{}{
				"name": "pv0004",
			},
			"spec": map[string]interface{}{
				"accessModes": "[ReadWriteOnce]",
				"capacity": map[string]interface{}{
					"storage": "5Gi",
				},
				"mountOptions": "[hard nfsvers=4.1]",
				"nfs": map[string]interface{}{
					"path":   "/tmp",
					"server": "172.17.0.2",
				},
				"persistentVolumeReclaimPolicy": "Recycle",
				"storageClassName":              "slow",
				"volumeMode":                    "Filesystem",
			},
		},
	}
)
