/*
Boilerplate 2024 test.
*/

// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var testNamespace = corev1.Namespace{
	ObjectMeta: metav1.ObjectMeta{
		Name: "test",
		Labels: map[string]string{
			"test": "testl",
		},
		Annotations: map[string]string{
			"test": "testa",
		},
	},
	Spec:   corev1.NamespaceSpec{},
	Status: corev1.NamespaceStatus{},
}
