// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import v1unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

var testUnstructuredNamespace = v1unstructured.Unstructured{
	Object: map[string]any{
		"apiVersion": "v1",
		"kind":       "Namespace",
		"metadata": map[string]any{
			"annotations": map[string]any{
				"test": "testa",
			},
			"labels": map[string]any{
				"test": "testl",
			},
			"name": "test",
		},
		"spec":   map[string]any{},
		"status": map[string]any{},
	},
}
