// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import v1unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

var nginxUnstructuredPod = v1unstructured.Unstructured{
	Object: map[string]any{
		"apiVersion": "v1",
		"kind":       "Pod",
		"metadata": map[string]any{
			"name": "nginx",
		},
		"spec": map[string]any{
			"containers": []any{
				map[string]any{
					"image": "nginx:1.14.2",
					"name":  "nginx",
					"ports": []any{
						map[string]any{
							"containerPort": 80,
						},
					},
				},
			},
		},
	},
}
