// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var nginxPod = corev1.Pod{
	ObjectMeta: metav1.ObjectMeta{
		Name: "nginx",
	},
}
