/*
Boilerplate 2025 test.
*/

// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var nginxPod = corev1.Pod{
	ObjectMeta: metav1.ObjectMeta{
		Name: "nginx",
	},
	Spec: corev1.PodSpec{
		Containers: []corev1.Container{
			corev1.Container{
				Name:  "nginx",
				Image: "nginx:1.14.2",
				Ports: []corev1.ContainerPort{
					corev1.ContainerPort{
						ContainerPort: 80,
					},
				},
			},
		},
	},
}
