// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var pv0003PersistentVolume = corev1.PersistentVolume{
	ObjectMeta: metav1.ObjectMeta{
		Name: "pv0003",
	},
}
