// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import v1unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

var pv0003UnstructuredPersistentVolume = v1unstructured.Unstructured{
	Object: map[string]any{
		"apiVersion": "v1",
		"kind":       "PersistentVolume",
		"metadata": map[string]any{
			"name": "pv0003",
		},
		"spec": map[string]any{
			"accessModes": []any{
				"ReadWriteOnce",
			},
			"capacity": map[string]any{
				"storage": "5Gi",
			},
			"mountOptions": []any{
				"hard", "nfsvers=4.1",
			},
			"nfs": map[string]any{
				"path":   "/tmp",
				"server": "172.17.0.2",
			},
			"persistentVolumeReclaimPolicy": "Recycle",
			"storageClassName":              "slow",
			"volumeMode":                    "Filesystem",
		},
	},
}
