// Code generated by reverse-kube-resource. DO NOT EDIT.

package examples

import v1unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

var exampleFooUnstructuredFoo = v1unstructured.Unstructured{
	Object: map[string]any{
		"apiVersion": "samplecontroller.k8s.io/v1alpha1",
		"kind":       "Foo",
		"metadata": map[string]any{
			"name": "example-foo",
		},
	},
}
