/*
Copyright 2021 The Kubermatic Kubernetes Platform contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by reverse-kube-resource. DO NOT EDIT.

package csicinder

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	samplecontrollerv1alpha1 "k8s.io/sample-controller/pkg/apis/samplecontroller/v1alpha1"
)

var (
	// Foo "example-foo"
	exampleFooReplicas1 int32 = 1

	exampleFooFoo = samplecontrollerv1alpha1.Foo{
		ObjectMeta: metav1.ObjectMeta{
			Name: "example-foo",
		},
		Spec: samplecontrollerv1alpha1.FooSpec{
			DeploymentName: "example-foo",
			Replicas:       &exampleFooReplicas1,
		},
	}
)
